#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

source 'https://rubygems.org'

gem 'middleman', '~> 3.4.0'
gem 'middleman-livereload', '~> 3.4.2'
gem 'middleman-autoprefixer', '>= 2.4.3'
gem 'middleman-minify-html', '>= 3.4.0'
gem 'middleman-syntax', '>= 2.0.0'
gem 'middleman-s3_sync', '>= 3.0.44'
gem 'middleman-search_engine_sitemap', '>= 1.3.0'

gem 'slim'
gem 'therubyracer'
gem 'oj'
gem 'redcarpet', '>= 3.2.3'
gem 'travis', '>= 1.8.2'
gem 'nokogiri'
gem 'rainbow'
gem "bootstrap-sass", ">= 3.3.5.1", require: false

platforms :mswin, :mingw do
  gem 'tzinfo-data'
  gem 'wdm', '~> 0.1.0'
end
